### PR TITLE
Update Iotics Public API to v1.0.1

### PR DESCRIPTION
**Pull request by StephanieBracaloni**

### CODE REVIEW

**Review by captnz — COMMENTED** [review]
Doesnt look like it has the changes?

**Comment by StephanieBracaloni** [comment]
My bad :woman_facepalming: 
Thank you @captnz for spotting it, it should be good now

**Review by captnz — APPROVED** [review]
lgtm

**Comment by StephanieBracaloni** [comment]
thks for the review :)

**Pull request merged**
